### PR TITLE
Fix #82

### LINKED ISSUE #82: Module Template Path Not Dash Delimited
When I create a module using the Expressive CLI Tooling, the template path name in `ConfigProvider.php` is not dash delimited.

### Code to reproduce the issue

`composer expressive module:create DbExamples`

### Expected results

```
<?php
// src/DbExamples/src/ConfigProvider.php
// ...

/**
 * Returns the templates configuration
 */
public function getTemplates() : array
{
    return [
        'paths' => [
            'db-examples'    => [__DIR__ . '/../templates/'],
        ],
    ];
}

// ...
```

### Actual results

```
<?php
// src/DbExamples/src/ConfigProvider.php
// ...

/**
 * Returns the templates configuration
 */
public function getTemplates() : array
{
    return [
        'paths' => [
            'dbexamples'    => [__DIR__ . '/../templates/'],
        ],
    ];
}

// ...
```

### PR DESCRIPTION
**Pull request by jbh**
- [x] Are you fixing a bug?
Bug details can be found in #82.

### CODE REVIEW

File: src/CreateHandler/CreateHandler.php [hunk 1]
```diff
@@ -37,10 +37,11 @@ public function __construct(string $classSkeleton = self::CLASS_SKELETON, string
     }
 
     /**
+     * @param string $class
```
Comment (michalbundyra) [inline src/CreateHandler/CreateHandler.php]: Please remove, it is redundant, doesn't give us any additional information than function signature. This is how we are doing now in ZF.

File: src/CreateHandler/CreateHandler.php [hunk 2]
```diff
@@ -37,10 +37,11 @@ public function __construct(string $classSkeleton = self::CLASS_SKELETON, string
...
      * @param array $additionalSubstitutions An associative array where the keys
      *     are the substitution strings to match, and the values are the associated
      *     values to substitute.
-     * @throws CreateHandlerException
+     * @return string
```
Comment (michalbundyra) [inline src/CreateHandler/CreateHandler.php]: The same about `@return` tag. We have defined RTH with the method declaration so it's useless.

File: src/CreateHandler/CreateHandler.php [hunk 3]
```diff
@@ -156,6 +159,7 @@ private function discoverNamespaceAndPath(string $class, array $autoloaders) : a
     }
 
     /**
+     * @param string $class
```
Comment (michalbundyra) [inline src/CreateHandler/CreateHandler.php]: Basically revert all changes in that file and everywhere where you changed PHPDocs, please.

File: src/CreateHandler/CreateHandler.php (hunk 1 above)
Comment (froschdesign) [inline src/CreateHandler/CreateHandler.php]: Please undo all these changes as they are not needed. The method declaration already contains this information!
Additionally the topic of this PR is the fix of #82 rather than adding more DocBlocks or clean up anything.

That makes the review easier. Thanks!

File: src/Module/Create.php [hunk 4]
```diff
@@ -134,8 +134,9 @@ private function createConfigProvider(string $modulePath, string $moduleName) :
 
     private function createTemplateNamespace(string $moduleName) : string
     {
-        $namespace = str_replace('\\', '-', $moduleName);
-        $namespace = strtolower($namespace);
-        return $namespace;
+        $pattern     = ['#(?<=(?:\p{Lu}))(\p{Lu}\p{Ll})#', '#(?<=(?:\p{Ll}|\p{Nd}))(\p{Lu})#'];
```
Comment (michalbundyra) [inline src/Module/Create.php]: I think these regular expressions are not very clear. Maybe will be worth to add some comment here? Why we need two? Is it the simplest way to do what we need? Not sure, but maybe will be better to use `CamelCaseToDash` filter from `zend-filter`?

File: test/Module/CreateTest.php [hunk 5]
```diff
@@ -129,7 +129,7 @@ public function testCreatesConfigProvider()
         $this->assertSame(1, preg_match('/\bnamespace MyApp\b/', $configProviderContent));
         $this->assertSame(1, preg_match('/\bclass ConfigProvider\b/', $configProviderContent));
         $command = $this->command;
-        $expectedContent = sprintf($command::TEMPLATE_CONFIG_PROVIDER, 'MyApp', 'myapp');
+        $expectedContent = sprintf($command::TEMPLATE_CONFIG_PROVIDER, 'MyApp', 'my-app');
```
Comment (michalbundyra) [inline test/Module/CreateTest.php:132]: I am not sure if that test case covers all changes in `createTemplateNamespace`. Maybe we need to add something more (we have there two regular expressions?).

**Review by michalbundyra — CHANGES_REQUESTED** [review]

File: src/CreateHandler/CreateHandler.php [hunk 6]
```diff
@@ -71,9 +70,6 @@ public function process(
         return $path;
     }
 
-    /**
-     * @throws CreateHandlerException
```
Comment (michalbundyra) [inline src/CreateHandler/CreateHandler.php]: Revert this change - see line 96.

File: src/Module/Create.php (hunk 4 above)
Comment (jbh) [reply src/Module/Create.php]: If we comment this and use `zend-filter` instead, we'll need to refactor the `TemplateResolutionTrait.php` also.

Comment (michalbundyra) [reply src/Module/Create.php]: Ok, I see, it is the same as there, so maybe we can reuse it somehow?

Comment (jbh) [reply src/Module/Create.php]: I had wanted to, but I couldn't think of a graceful way of doing it. `TemplateResolutionTrait.php` was meant for `CreateHandler`. I suppose I could still use it in `Module`, but it just felt wrong to do so.

Comment (jbh) [reply src/Module/Create.php]: Is it not a faux pas to use `CreateHandler\TemplateResolutionTrait` in `Module\Create`? If it isn't, I'll do that instead.

Comment (michalbundyra) [reply src/Module/Create.php]: Ok, let leave it as it is, and we will see what @weierophinney is gonna say. I would like to re-use the same functionality. I can see couple options, and the easiest would be extracting this function to separate Trait and reuse it in both places.

Comment (jbh) [reply src/Module/Create.php]: Yes, those were my first thoughts as well, but I was trying to get this in working order as soon as possible, cause it's broken right now. :)

Comment (michalbundyra) [reply src/Module/Create.php]: Sure, leave it for now, and we will see what @weierophinney decide.

**Review by michalbundyra — APPROVED** [review]

File: src/Module/Create.php (hunk 4 above)
Comment (jbh) [reply src/Module/Create.php]: And if we separate it to another trait, where will that live? I suppose we'll need a `Trait` directory for common traits. I'll wait for @weierophinney to weigh in.

File: test/Module/CreateTest.php (hunk 5 above)
Comment (jbh) [reply test/Module/CreateTest.php:132]: This test is just testing if the ConfigProvider is the right format. There could be more tests for template namespace.

File: src/Module/Create.php (hunk 4 above)
Comment (weierophinney) [reply src/Module/Create.php]: I'd put common traits in the source root, honestly, since each command is in its own subdirectory.

File: test/Module/CreateTest.php (hunk 5 above)
Comment (weierophinney) [reply test/Module/CreateTest.php:132]: I'd say that once you extract the trait, you should add the additional tests as well.

**Review by weierophinney — CHANGES_REQUESTED** [review]
Extract the trait to the source root, and add the tests as indicated by @webimpress , and I think this is good to go.

Thanks, @jbh !

**Comment by jbh** [comment]
Will do. :)

**Comment by jbh** [comment]
I'll write tests either tonight or in the morning, but I wanted feedback on moving the entire trait to the source root. I just couldn't find a good reason to create a new trait and move just the one method alone.

**Comment by jbh** [comment]
So the regex as I understand it works as such. The first, `(?<=(?:\p{Lu}))(\p{Lu}\p{Ll})`, matches indefinite uppercase and uppercase-lowercase. It will match `LLL...L` and `Ll`. The second, `(?<=(?:\p{Ll}|\p{Nd}))(\p{Lu})`, is for module names with numbers in them. I believe the two test cases I added will cover these. I might have missed a test, but I can't think of anymore currently.

**Review by weierophinney — APPROVED** [review]

**Comment by weierophinney** [comment]
@jbh — I've reset this against develop, as it's a slight behavior change, and it's best to call those out at minor releases. I rebased your branch, and then applied one fix (we import all classes, interfaces, and traits used normally).

Thanks a ton for this! I also got to learn about unicode `\p{}` characters sets in the process, which was awesome!
